### PR TITLE
Weekly format fix #2

### PR DESCRIPTION
**Pull request by joblo2213**
_This is the **2nd** one and only optional but not guaranteed weekly fix for your formatting._  
_All other format fixes are not affiliated with these well tested and thought through weekly fixes and may therefore be inferior._ 🔥 

Just to remind you:
> grafik
> grafik

All other changed files have been checked and meet our high file formatting standards. 😉 

Closes #30.

### CODE REVIEW

**Comment by kegelsknight** [comment]
I think you mean `thought through`?

**Comment by derNiklaas** [comment]
> All other changed files have been checked and meet our high file formatting standards. 😉

You are actually wrong. 
Have a look at .gitignore :P

**Comment by joblo2213** [comment]
> 
> 
> > All other changed files have been checked and meet our high file formatting standards. 😉
> 
> You are actually wrong.
> Have a look at .gitignore :P

I did. But have you? 

[grafik](https://github.com/sebinside/CraftBlock/pull/31/files)

**Comment by derNiklaas** [comment]
whoops. lol

**Pull request merged**
