### PR TITLE
Set nether void world with yunomakegoodmap instead

### PR DESCRIPTION
**Pull request by voruti**
Fix for #50.

yunomakegoodmap and Void Island Control were conflicting with each other (I didn't know that yunomakegoodmap is installed). Since yunomakegoodmap is a better solution, I adjusted the template map for the use of this mod.

@sebinside: Remove Void Island Control again :D

### CODE REVIEW

**Comment by voruti** [comment]
No, wait! :sweat_smile:
I think yunomakegoodmap will also make the end completely void!

**Comment by voruti** [comment]
This is what yunomakegoodmap does to the end.

**Comment by voruti** [comment]
The decision is up to @sebinside:
"More clean" solution yunomakegoodmap mod with [this](https://github.com/sebinside/CraftBlock/pull/51#issuecomment-907822881) as the end dimension vs. Void Island Control mod with normal end dimension but many unused mod features.

**Comment by voruti** [comment]
This would be the end with the Void Island Control mod. The outer end island are there aswell.

**Comment by sebinside** [comment]
Worked, thank you!

**Pull request closed without merging**
