### PR TITLE
Fix rain only on main island

### LINKED ISSUE #58: Its only raining on the main island
When you build away from the main island, there is no rain, because the biome is "The Void".

### LINKED ISSUE #64: you can only using the main island for mob spawning
you can only use the main island for mob spawning because only the main island has normal biomes and all Biome space around the main island is void

### PR DESCRIPTION
**Pull request by voruti**
Fixes #58, fixes #64.

### CODE REVIEW

**Comment by voruti** [comment]
level.dat:
level_diff

**Comment by voruti** [comment]
Fixes #64

**Comment by joblo2213** [comment]
You might delete your comment and edit your initial post so it contains the fix message.  
That way the Issue will not only be mentioned but also linked so this PR automatically closes it.

**Comment by voruti** [comment]
For already generated world on would have to use WorldEdit to change all "The Void" chunks or delete them, if they are empty.

**Pull request merged**
