### PR TITLE
Use gradle to build the pack

### PR DESCRIPTION
**Pull request by noeppi-noeppi**
This makes it automatable ad you don't need the CurseForge app

Maybe later I can add something to automatically upload the pack to CurseForge

Contains the ModList of release 1.0.0. All changes to the ModList made in 1.1.0 must still be added to `modlist.json`

### CODE REVIEW

**Comment by noeppi-noeppi** [comment]
To build the pack, use `./gradlew build`. This will build the pack in `build/target`

**Comment by sebinside** [comment]
Whats the reason for moving all the files to `data`?

**Comment by noeppi-noeppi** [comment]
> Whats the reason for moving all the files to data?

It is required for the PackDev gradle plugin

> And related: Will the modpack still be directly playable via the CurseForge launcher if all configs etc. are located in data/common and not in the root modpack folder?

No. You play the game with `gradlew runClient`. Or you need to build the project and import it into the curse launcher

**Comment by noeppi-noeppi** [comment]
The goal of PackDev is to have everything in one place and don't need the CurseForge app any longer. So it's not the goal of the PackDev plugin to keep things usable with the Curse app. With a bit of work, it might be possible but it is not intended and I won't support this in PackDev.

**Comment by joblo2213** [comment]
The large problem that i see here is that it forces people to use this workflow and nothing else. It not only breaks the curseforge app but also use with multimc.
This makes contributing much harder and more annoying for people that are not used to gradle.

**Comment by noeppi-noeppi** [comment]
You are forced to this worklow to build mods as well. It is a trade off. I (well Melan ad me) tries some python scripts to manage the mod list and building releases, which would allow you to use any launcher you want. But that did not really work well either.

Gradle is the de facto standard for launching anything modding related in development. And it is possible to use the current workflow with MultiMC. If I find the time, I'll add a task into the gradle plugin to generate the required files but doing that manually is not that hard.

**Comment by sebinside** [comment]
Classified as level 7 overkill. I'm very sorry but @joblo2213 forced me to close this. xoxo

**Comment by joblo2213** [comment]
Thats a lie. @derNiklaas is to blame.

**Comment by derNiklaas** [comment]
nope. @joblo2213's fault

**Pull request closed without merging**
