### PR TITLE
Spike: Make Nether void with Void Island Control mod

### PR DESCRIPTION
**Pull request by voruti**
The [Void Island Control](https://www.curseforge.com/minecraft/mc-mods/void-island-control/files/2666967) mod is way to overpowered for just voiding the Nether. But it works.

### CODE REVIEW

**Comment by voruti** [comment]
Nether is void **without** structures; End is vanilla

**Comment by sebinside** [comment]
In my testing, the nether is still normal not void...

**Comment by voruti** [comment]
Did you install the mod?
> The [Void Island Control](https://www.curseforge.com/minecraft/mc-mods/void-island-control/files/2666967) mod [...].

This pull request can only supply the configuration file...

**Comment by sebinside** [comment]
I did ;) But nothing happens at all. Strange, since the config looks fine to me... 
image

**Pull request merged**
