### PR TITLE
Newlines :)

### PR DESCRIPTION
**Pull request by derNiklaas**
we add newlines around here.

closes #31

### CODE REVIEW

**Comment by joblo2213** [comment]
This should be in _weekly format fix #2_.

**Comment by derNiklaas** [comment]
@joblo2213 You're not the only one who is allowed to do format fixes :P

**Comment by joblo2213** [comment]
But I'm the only one that does it properly.

**Comment by kiriDevs** [comment]
@joblo2213 The question is - why wasn't it included in `#1`?

**Comment by joblo2213** [comment]
@kiriDevs _Obviously_ because the errors were introduced later. 🙄

**Comment by kiriDevs** [comment]
@joblo2213 I'd call 11:45 on a Sunday as a less-than-optimal time to open the format-fix PR - we all know that format errors are introduced every week on a Sunday around 11:00 to 13:00 :laughing:

**Comment by joblo2213** [comment]
??? What the actual fuck are you talking about? #28 was a week ago at around `13:30` 🙄

**Comment by kegelsknight** [comment]
You should start to squash your commits. https://gitbetter.substack.com/p/how-to-squash-git-commits
This is pretty embarrasing to have 3 commits for 3 oneline changes.

**Comment by derNiklaas** [comment]
If you really want the PR 🤷‍♂️ 
Have your fake internet points

**Comment by derNiklaas** [comment]
Also @kegelsknight I was using the GitHub Website where you can't do that. On good Git websites you can squash the commits when merging a PR.

**Pull request closed without merging**
