### PR TITLE
CraftBlock Map

### PR DESCRIPTION
**Pull request by joblo2213**
# The CraftBlock map is finished

grafik

Hope I mentioned any active builder, if I forgot you pls @ me.

### CODE REVIEW

**Comment by joblo2213** [comment]
Just added an advancement: 
icon
Player has to collect all 8 (_skate702, CastCrafter, jelugu, liketechnik2000, noeppi_noeppi, ruvoti13, syncopsta, ungefroren_) player heads hidden on the map.

**Comment by sebinside** [comment]
Out of curiosity (and because we'll have to handle it too): What about the nether?

**Comment by joblo2213** [comment]
Hasn't been worked on yet, will generate normal. Also don't know if supported by lockdown. I'll check it out and report. 

What would be a desired behaviour for the nether?

**Comment by joblo2213** [comment]
I checked and we can add any prebuild nether & end map using lockdown too. 
Note that there is currently no way to generate a void nether map as the generator can only be tweaked using mods (so if a player would leave the prebuild chunks he would find a default nether).

**Comment by voruti** [comment]
I would prefer an "empty" nether. That would be (enforced by some mod)
1. completely empty, or
2. empty but with structures present (like in SkyFactory 2, I think).

---
In a pre-build nether you wouldn't know where the player spawns ...

**Pull request merged**
