### PR TITLE
Remove Pebbles once and for all

### PR DESCRIPTION
**Pull request by J0B10**
grafik

### CODE REVIEW

**Comment by J0B10** [comment]
be carefull tough. You can add items to pebbles ore-dic using `<ore:pebble>.add(item)`.
Any item with this entry will vanish in the blink of an eye when dropped in the world.

**Comment by voruti** [comment]
Does this have an impact on performance?

**Comment by J0B10** [comment]
I observed none. 

Therretically it should not have one as the event listener is only called if an entity is spawned and everything is O(1)

**Comment by J0B10** [comment]
I did some further testing & profiling to verify that it has no big impact on performance:

<details>
<summary>This house is build from command blocks, each one spawning 20 pebbles per second</summary>

</details>

<details>
<summary>Event Handling of all command blocks still took only 7% of server tick time while keeping the server at 3.4ms/tick<br>(which is extremely low, 50ms/tick is maximum for a stable tick rate)</summary>

</details>

Therefore performance of event handlers such as this one should be of no concern.

**Pull request merged**
